
management.endpoints.web.exposure.include: '*'
management.endpoint.health.show-details: always


resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true
      slidingWindowSize: 10
      minimumNumberOfCalls: 5
      slidingWindowType: TIME_BASED
      permittedNumberOfCallsInHalfOpenState: 3
      automaticTransitionFromOpenToHalfOpenEnabled: true
      waitDurationInOpenState: 2s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      recordExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
resilience4j.retry:
  configs:
    default:
      maxRetryAttempts: 3
      waitDuration: 200
      retryExceptions:
        - org.springframework.web.client.HttpServerErrorException
        - java.io.IOException
        
resilience4j.bulkhead:
  configs:
    default:
      maxConcurrentCalls: 200

resilience4j.thread-pool-bulkhead:
  configs:
    default:
      maxThreadPoolSize: 6
      coreThreadPoolSize: 3
      queueCapacity: 3

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: false
      limitForPeriod: 20
      limitRefreshPeriod: 2s
      timeoutDuration: 0
      eventConsumerBufferSize: 100
